### ISSUE TITLE
CLA Website shows PHP error

### ISSUE THREAD

**Issue by Laborratte5** [writefreely/writefreely#1017]
### Describe the bug
I don't know if this is the right place for it,
but the site for the CLA (https://phabricator.write.as/L1) returns an php error

### Steps to reproduce (if necessary)
1. Visit https://phabricator.write.as/L1

### Expected behavior
What should've happened?
The CLA should be displayed

**Comment by thebaer** [comment]
Thanks for reporting this! That URL should now redirect to the correct location at https://todo.musing.studio/L1. But I'll update our docs to reflect that, too.
