### ISSUE TITLE
Blogs on custom domains are only federated on Write.as, not their canonical domains

### ISSUE THREAD

**Issue by tildelowengrimm** [writefreely/writefreely#1039]
### Preamble
Blogs hosted on Write.as can be served for custom domains outside of Write.as. The _Customize_ page for a blog has a _Preferred URL_ section, in which the third option is _Custom domain_. For instance, my Write.as blog is at `writing.tildelowengrimm.com` (though it is also at `write.as/tilde` and `tilde.write.as`). In the _Updates_ section of the _Customize_ page is a _Federation_ checkbox, which shows something like `@_____@custom.domain.example`. The person editing their blog settings can enter a string blank space. For instance, I have entered the string `tilde-is-writing` for a complete string of `@tilde-is-writing@writing.tildelowengrimm.com`, which looks a lot like a fediverse handle.

### Expected vs observed behavior
**Expected.** My reasonable expectation as a person using the _Customize_ page is that when the _Federation_ box is checked, my blog will be available on the fediverse at the listed handle (for me: `@tilde-is-writing@writing.tildelowengrimm.com`). This is not the case.

**Observed.** In fact, the blog is only federated under the `write.as` domain. For instance, my blog is ostensibly federated as `@tilde@write.as` rather than the expected `@tilde-is-writing@writing.tildelowengrimm.com`. (I will note that I have not been able to validate my blog being federated even under `write.as` from my preferred fediverse instance, but another forum commenter posted what seems to be a screenshot, so that's probably a separate issue)

**Explanation.** This cannot be correct because the information in the interface does not match the actual behavior. Either the rendering of the _Federation_ option on the _Customize_ page is incorrect or the actual federation behavior is incorrect (or incomplete).

This observed is [corroborated by another observer](https://discuss.write.as/t/federation-troubleshooting/227/44) on the forum, with a separate blog.

### Comments
My expectation using Write.as is that it is (1) a blog tool which (2) is hosted for me for a fee or I can host myself (3) under my own domain, & (4) federates on the fediverse. I expect that points 3 & 4 are both true together and are not exclusive. I believe that the impression given by the _Customize_ page is correct, and that the actual behavior of only federating under the `write.as` domain is incorrect.

**Comment by thebaer** [comment]
I believe this was an issue specifically with our Write.as instance not verifying the custom domain correctly ([see this comment](https://discuss.write.as/t/federation-issue/13102/5)). Since that's fixed there, I'll close this.
