### ISSUE TITLE
Tool bar word count is incorrect for Chinese Language

### ISSUE THREAD

**Issue by deyigifts** [writefreely/writefreely#1041]
### Describe the bug
Explain what the bug is, in as much detail as possible...

### Steps to reproduce (if necessary)
Write some Chinese words in post, after publish, ends in incorrect word count in toolbar display.
![2024-09-22_111827](https://github.com/user-attachments/assets/b3ee114b-f1c3-4267-a079-4ae8cb96b49e)

### Expected behavior
What should've happened?
Correct word count should be displayed. As shown above more than `5 words` should get counted.

### Application configuration
 - **Single mode** 
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**:
v0.15.0

**Comment by vtyeh** [comment]
I looked into this issue and it seems that the editor treats each sentence as its own word, including any commas. Word count is separated by space.

**Examples**
1 word: 我喜歡喝波霸奶茶。
1 word: 我喜歡喝波霸奶茶，我喜歡喝波霸奶茶。
1 word: 我喜歡 喝波霸奶茶,我喜歡喝波霸奶茶。
2 words: 我喜歡喝波霸奶茶， 我喜歡喝波霸奶茶。
2 words: 我喜歡 喝波霸奶茶, 我喜歡喝波霸奶茶。
8 words: 我 喜 歡 喝 波 霸 奶 茶。

The correct word count would be 5:
1. 我 
2. 喜歡 
3. 喝 
4. 波霸 
5. 奶茶

However, creating the rules for Chinese word count is extremely difficult and may not apply to other languages such as Korean or Japanese. There is an interesting discussion in [this thread](https://github.com/vkbo/novelWriter/issues/1657). Specifically [this comment](https://github.com/vkbo/novelWriter/issues/1657#issuecomment-1909676578).

I do not have a solution for this at the moment, but thought I might share these insights for anyone who wants to tackle this challenge.

**Comment by deyigifts** [comment]
> may not apply to other languages such as Korean or Japanese. There is an interesting discussion in this thread. Specifically [this comment](https://github.com/vkbo/novelWriter/issues/1657#issuecomment-1909676578).
> 
> I do not have a solution for this at the moment, but thought I might share these insights for anyone who wants to tackle this challenge.

Thanks for the reply, it seems that this is a duplicated issue. I would close this issue and disuse over there.  The *Conception B* looks promising, since word split of Chinese sentence usually reply on the natural language processing module.
