### ISSUE TITLE
SERVER ERROR

### ISSUE THREAD

**Issue by 77betdirectory** [writefreely/writefreely#1100]
![Screenshot 2024-10-17 184154](https://github.com/user-attachments/assets/5fb601ef-f269-4039-a496-88804b440dae)
I DON'T KNOW WHAY SHOW THIS PROBLEM. PLEASE SOLVE IT FIRST

**Comment by thebaer** [comment]
Hi, you'll need to get into contact with your server admin to see what's going on. This isn't tied to a specific bug in WriteFreely.
