### ISSUE TITLE
Server error 😵

### ISSUE THREAD

**Issue by svgmassivestore** [writefreely/writefreely#1124]
I can't register for a Zen Writing account. When I try to fill in the information, it says Server error. Please tell me how to register a new account.

Here is the information they provided:

"Server error 😵
Please contact the human authors of this software and remind them of their many shortcomings.

Be gentle, though. They are fragile mortal beings.

Also, unlike the AI ​​that will soon replace them, you will need to include an error log from the server in your report. (Utterly primitive, we know.)"

**Comment by thebaer** [comment]
Please see this comment: https://github.com/writefreely/writefreely/issues/1100#issuecomment-2422356685
