### ISSUE TITLE
[PROGRAMMER ERROR] WARNING: Collection.hostName is empty! ... on selecting the Customize menu item

### ISSUE THREAD

**Issue by theapiarist** [writefreely/writefreely#1146]
### Describe the bug
The following error appears in the debug log, or in syslog

Nov 26 22:24:03 my-vps writefreely[17985]: ERROR: 2024/11/26 22:24:03 collections.go:273: [PROGRAMMER ERROR] WARNING: Collection.hostName is empty! Federation and many other things will fail! If you're seeing this in the wild, please report this bug and let us know what you were doing just before this: https://github.com/writefreely/writefreely/issues/new?template=bug_report.md

### Steps to reproduce (if necessary)
1. Logged in, select the Customize menu

### Expected behavior
I presume I shouldn't have seen that error ;-)

### Application configuration
 - Single user
 - MySQL
 - **Open registration?** not sure what this means, sorry
 - **Federation enabled?** Yes

**Version or last commit**: WriteFreely 0.15.1

**Comment by theapiarist** [comment]
This is a duplicate of [#907](https://github.com/writefreely/writefreely/issues/907) which I should have found before posting

**Comment by thebaer** [comment]
No problem! Thanks for bringing it up, and we'll address everything over on that issue.
