### ISSUE TITLE
Including image descriptions on page description makes the description meta less readable

### ISSUE THREAD

**Issue by ricardojmendez** [writefreely/writefreely#306]
### Describe the bug

If there is an image at the start of the article, and this image includes a description, the meta for the article will include it, followed by the first paragraph.

This causes article previews to end up being less readable.

I'd have expected the description meta to start with the first paragraph.

### Steps to reproduce (if necessary)

- Create a new article
- Add an title, then before the first paragraph, include an image with a description
- The page's meta description will include the image description

### Expected behavior

The page's description should not include anything about the image and start at the first paragraph

**Comment by thebaer** [comment]
Thanks for catching this, @ricardojmendez! Definitely want to improve this.

I've opened an issue for this in the library that processes text for the page descriptions: writeas/go-strip-markdown#2. After fixing this there, we'll get it into WF.
