### ISSUE TITLE
Post actions on articles list are difficult to trigger on touch screen devices

### ISSUE THREAD

**Issue by Crocmagnon** [writefreely/writefreely#309]
### Describe the bug
Accessing post modification buttons on an touch screen is difficult because they only appear on hover.
![image](https://user-images.githubusercontent.com/3630554/81922150-fccea900-95db-11ea-98da-d0b019be0de6.png)

### Steps to reproduce (if necessary)
1. Go to the articles list
2. Try to click on a button on a device with a touch screen and no mouse pointer
3. It's very hard, you need to think about where the button is going to be and try to tap it

### Expected behavior
The buttons should always be visible (maybe dimmer) or in a menu that we can click on safely without triggering an action.

### Application configuration
 - **Single mode or Multi-user mode?**  Any
 - **Database?** [mysql/sqlite] Any
 - **Open registration?** [yes/no] Any
 - **Federation enabled?** [yes/no] Any

**Version or last commit**: v0.12.0

**Comment by thebaer** [comment]
Thanks for the report, @Crocmagnon! This has been brought up before in #94. But that report also mentions a few other accessibility issues, so I'll leave this open to address the mobile problem in particular. I'm currently working around other aspects of the menu design / UX right now, so I can address this.

**Comment by Crocmagnon** [comment]
Thanks for your response! I would love to see that coming to a future release 😊

**Comment by Crocmagnon** [comment]
I just realized that in fact the Drafts UI works fine, if it helps :)

**Comment by thebaer** [comment]
From https://github.com/writeas/writefreely/issues/359#issuecomment-667707275 by @wiwie:

> My proposal is that the links should always be shown on mobile browsers.

I think this is a good, simple way to fix this.

**Comment by Crocmagnon** [comment]
Why not every browser? So that users have the same UI everywhere?

And just out of curiosity, is it even possible to detect Safari on an iPad among other user agents ? I thought Apple modified it to send the same as safari on desktop so users would be served with desktop sites and not mobile ones.

**Comment by wiwie** [comment]
@Crocmagnon I guess the original intention of hiding the section links when not used was to keep the UI as lightweight as possible. While I actually also do like that approach and the minimal resulting ui, I'm also inclined to agree with you to say that the current approach of hiding the action links is probably a bad idea everywhere from a usability/accessibility perspective. For example, are screen readers able to read those links? If not, it would basically exclude blind people from using writefreely.

An approach to keep the UI minimal while still being accessible could be to add a small collapsible menu (eg drop down). I would think that if implemented correctly these can be interpreted by screen readers also.

**Comment by DavePolaschek** [comment]
Note that Safari on iPad masquerades as safari on Mac OS, so for at least that one mobile browser, "is this a mobile browser?" is likely to fail.

I tried using the classic editor, mostly to have easier "set a title" functionality, but there were a lot of things failing there when trying to use if from safari on an iPad.

**Comment by cblte** [comment]
As a quick fix: you could use some css styling to have the links always shown. 
Just add
```
.hidden {
  opacity: 1;
}
```
anywhere to your custom css.

**Comment by DavePolaschek** [comment]
That works, thanks!

Interesting thing from a "fixing the bug" POV is that the commands don’t seem to be there when looking at an individual post, but they are there when looking at the whole list on the blog. That’s almost the inverse of what I was expecting. When I want to interact with a single post, I go to that post, rather than going to its parent blog.

**Comment by thebaer** [comment]
Mistakenly closed this with a different commit. #449 will close this, once merged.
