### ISSUE TITLE
Links have rel="nofollow"

### ISSUE THREAD

**Issue by Crocmagnon** [writefreely/writefreely#314]
### Describe the bug
Links added by the user on an article or a pinned page have a `rel="nofollow"` attribute.

### Steps to reproduce (if necessary)
Add a link in an article, either with markdown or HTML.
If the link is HTML and the user explicitly specifies another value for the `rel` attribute, this value is overridden when rendering the page.

### Expected behavior
I see two issues with this:

* This prevents Mastodon profile validation (which requires a `rel="me"`)
* This may reduce the visibility of the blogs since search engines apparently respect this directive

From the MDN:
> Indicates that the linked document is not endorsed by the author of this one, for example if it has no control over it, if it is a bad example or if there is commercial relationship between the two (sold link).
- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types

IMHO this:
* shouldn't be applied at all on internal links (links to `href="#something"` or to other pages of the blog)
* should be applied by default on external links if the user doesn't specify anything else via a custom HTML anchor.

### Application configuration
 - **Single mode or Multi-user mode?**  single
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: 037fc40

**Comment by dimobelov** [comment]
Yes, just add Config option follow/nofollow and use it here https://github.com/writeas/writefreely/blob/9be05ef32e818e1be759fbca34533b9430b8d79e/postrender.go#L62

**Comment by thebaer** [comment]
Thanks for bringing this up, @Crocmagnon. I just opened #482 to solve this. I think a no-brainer fix includes disabling `rel="nofollow"` for single-user blogs, so that's what I've done so far. But I'd love to know everyone's thoughts on other situations where we might also disable it.
