### ISSUE TITLE
Import from Safari does not allow .md file upload

### ISSUE THREAD

**Issue by lukehoersten** [writefreely/writefreely#334]
### Describe the bug
When importing from Safari, the file upload dialog box does not allow for selecting other file extensions than `.txt` so `.md` doesn't work.

### Steps to reproduce (if necessary)
From Safari:
1. Go to 'Import posts'
2. Click on 'Choose files'
3. Try to select a markdown file

In Firefox, the file upload dialog has a way to disregard the site-specific file type. Safari does not.

### Expected behavior
I should be able to select a `.md` markdown file to import.

**Version or last commit**:

Latest

**Comment by thebaer** [comment]
Thanks for the report, @lukehoersten! Does anyone familiar with Safari have ideas on some workarounds here? Maybe some JS-based browser detection?
