### ISSUE TITLE
Upgrade to v0.12.0 caused special characters to turn to garbage

### ISSUE THREAD

**Issue by carbontwelve** [writefreely/writefreely#441]
### Describe the bug
When upgrading to v0.12.0 following the instruction `ALTER DATABASE writefreely CHARACTER SET latin1 COLLATE latin1_swedish_ci;` caused all emoji and special characters to become corrupted.

For example see the below screen shot, there was an emoji at the end of the post and the pull out to the right was bookended by curly quotes:
![image](https://user-images.githubusercontent.com/464699/111075531-521b6580-84e0-11eb-8145-9f0c3d79e68d.png)

What I suspect is happened is the altering of the database character set wasn't followed by a conversion of the character set in the database content.

**Comment by thebaer** [comment]
It looks like columns on your tables might not have been set correctly... I'd need to check which version this was supposed to happen on. But could you run this query and share the output?

```
SHOW FULL COLUMNS FROM posts;
```

We're looking for the `content` column to have a `collation` of `utf8mb4_bin`.

**Comment by carbontwelve** [comment]
The `content` column is showing as having a `collation` of `utf8mb4_bin`. 

I have looked at a backup of the database from before migrating and its showing the same. The only thing that seems to have been changed is that the database as a whole has `latin1_swedish_ci` where as previously it was `utf8mb4_general_ci` like all my other applications databases.

**Comment by thebaer** [comment]
Sorry for the slow response here. I'm really not sure what would cause this, unfortunately, especially if the collation on that column hasn't changed. The best thing to do might be to revert to your previous character set and collation.

**Comment by thebaer** [comment]
Since we haven't heard about this affecting anyone else, and it should be fixed from the start with our updated installation instructions, I'm not sure there's anything actionable on this issue, so I'll close it.
