### ISSUE TITLE
Blocking fonts breaks only one menu

### ISSUE THREAD

**Issue by xundeenergie** [writefreely/writefreely#459]
### Describe the bug
I have browser.display.use_document_fonts set to 0 in my firefox as security-feature. This breaks only one menu. All others are working as expected. Look at the screenshot. 

![screenshot_writefreely_broken_menu](https://user-images.githubusercontent.com/5894829/116859370-368b2c00-ac00-11eb-8448-33599908b128.png)

Setting this to 1 the menu is correct.

### Steps to reproduce (if necessary)
1. Go to 'about:config'
2. Set browser.display.use_document_fonts to 0
3. Go to writefreely and hover over "Drafts" in writing-mode

### Expected behavior
The fonts in this menu should be the same as in every other menu in writefreely too.

### Application configuration
 - **Single mode or Multi-user mode?** Multiuser 
 - **Database?** [mysql/sqlite] mysql
 - **Open registration?** [yes/no] no
 - **Federation enabled?** [yes/no] yes

**Version or last commit**: v0.12.0

**Comment by xundeenergie** [comment]
I found, the broken Menu has this CSS-Styles (from Firefox developer tools)
`header nav#user-nav a {
    font-size: 1.2em;
    font-family: 'Open Sans','Segoe UI',Tahoma,Arial,sans-serif;
}
header nav#user-nav a {
    font-size: 1.2em;
    font-family: 'Open Sans','Segoe UI',Tahoma,Arial,sans-serif;
}
.material-icons {

    font-family: 'Material Icons';
    font-weight: 400;
    font-style: normal;
    font-size: 24px;
    display: inline-block;
    width: 1em;
    height: 1em;
    line-height: 1;
    text-transform: none;
    letter-spacing: normal;
    word-wrap: normal;
    white-space: nowrap;
    direction: ltr;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
    -moz-osx-font-smoothing: grayscale;
    font-feature-settings: 'liga';

}
`

the other menu haas only this CSS-Style
`header nav#user-nav a {
    font-size: 1.2em;
    font-family: 'Open Sans','Segoe UI',Tahoma,Arial,sans-serif;
}`

**Comment by thebaer** [comment]
Thanks for the report, @xundeenergie. Do you have any resources on what security improvements that browser feature gives you? From my own knowledge, I'm not sure of why someone might be motivated to disable icon fonts, and hence if it's worth supporting that browser feature in the near term.

**Comment by thebaer** [comment]
I'll close this now, but please feel free to respond whenever you can.
