### ISSUE TITLE
Date in Title

### ISSUE THREAD

**Issue by Tealk** [writefreely/writefreely#470]
### Describe the bug
If you enter a date in the title `12. april` then it becomes `1. april`
in the database it is correct
but if you write `12.april` it works without problems

### Steps to reproduce (if necessary)
1. Create a new post
2. enter a date in the title
3. save the post

### Expected behavior
the correct date should be displayed

### Application configuration
 - **Single mode or Multi-user mode?** Multi-user mode
 - **Database?** mysql
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: 0.13.0

**Comment by thebaer** [comment]
Good catch, @Tealk -- thanks for the report! I was able to verify this. I believe it's because we render the title as Markdown (to preserve title links), so we're parsing this as the first item in a list, instead of an arbitrary number followed by a dot. I'm looking into a fix now.
