### ISSUE TITLE
 multi-user instance not seem to render HTML correctly

### ISSUE THREAD

**Issue by mkyos** [writefreely/writefreely#473]
Why does the front page of my multi-user instance not seem to render HTML correctly, as shown in the figure：

<img width="1463" alt="截屏2021-06-23 12 48 00" src="https://user-images.githubusercontent.com/72077265/123037546-6ba64480-d421-11eb-89b7-d826d96aa789.png">

**Comment by thebaer** [comment]
Hi, are you running the official release or compiling it from source?

If you're compiling it, you probably still need to run: `make ui` to generate the stylesheets. Otherwise, I'd guess that something in your configuration is blocking access to the `css/` directory.

**Comment by mkyos** [comment]
> Hi, are you running the official release or compiling it from source?
> 
> If you're compiling it, you probably still need to run: `make ui` to generate the stylesheets. Otherwise, I'd guess that something in your configuration is blocking access to the `css/` directory.

Yes, thank you for your reply! I found the reason: the public URL was not set to HTTPS://**** in the config, but my website was set to HTTP redirect to HTTPS.
