### ISSUE TITLE
Unordered list in a classic editor appears "\" automatically.

### ISSUE THREAD

**Issue by mkyos** [writefreely/writefreely#480]
### Describe the bug
When editing a post again, the unordered list in the classic editor automatically appears `\`.

https://user-images.githubusercontent.com/72077265/123500624-0bf2a800-d672-11eb-85bc-75363185ece3.mp4

### Application configuration
 - **Single mode** 
 - **Database?** [sqlite]
 - **Open registration?** [no]
 - **Federation enabled?** [yes]

**Version or last commit**:0.13.0

**Comment by thebaer** [comment]
Thanks for reporting this, @mkyos, I've noticed the same thing. I'll take a look at this and see if I can fix it for the 0.13.1 release.
