### ISSUE TITLE
Chinese tag is not supported

### ISSUE THREAD

**Issue by mkyos** [writefreely/writefreely#491]
### Describe the bug
Chinese tag is not supported

https://user-images.githubusercontent.com/72077265/124498903-b3e53f80-ddef-11eb-8d19-2e76373253cb.mp4

### Application configuration
 - **Single mode** 
 - **Database?** [sqlite]
 - **Open registration?** [yes]
 - **Federation enabled?** [yes]

**Version or last commit**:0.13.1

**Comment by thebaer** [comment]
Thanks for reporting this, @mkyos. It's actually a duplicate of #219, so let's discuss and track any fixes on that issue.
