### ISSUE TITLE
Unable to update blog customization settings.

### ISSUE THREAD

**Issue by AverytheFurry** [writefreely/writefreely#495]
### Describe the bug
I'm unable to update my blog's customization settings.

### Steps to reproduce (if necessary)
1. Go to example.com/me/c/blognamehere
2. Click on Save changes
3. See error
![image](https://user-images.githubusercontent.com/47131867/125179704-4f0b5a00-e1e0-11eb-8a5e-9f14aa100635.png)

```
Jul 11 00:20:32 localhost writefreely[23832]: ERROR: 2021/07/11 00:20:32 database.go:929: Unable to insert monetization_pointer value: near "DUPLICATE": syntax error
Jul 11 00:20:32 localhost writefreely[23832]: ERROR: 2021/07/11 00:20:32 collections.go:1087: Couldn't update collection:
```
### Expected behavior
The settings should be updated, but instead it errors.

### Application configuration
 - **Single mode or Multi-user mode?** Multi user
 - **Database?** Sqlite
 - **Open registration?** No
 - **Federation enabled?** Yes

**Version or last commit**: 0.13.1

**Comment by thebaer** [comment]
Thanks for reporting this! We probably need to update this query to work with SQLite, in addition to MySQL.

**Comment by AverytheFurry** [comment]
> 
> 
> Thanks for reporting this! We probably need to update this query to work with SQLite, in addition to MySQL.

Don't want to nag or rush but I'm curious when this will be fixed, as it's preventing a lot of functionality. Should I just switch to MySQL? I don't know what the difference is tbh and just did SQLite because it was easier lol.

**Comment by thebaer** [comment]
Switching to MySQL would fix it in the short term, if that's easy for you to do! SQLite is definitely easier in many ways, since you don't need to set up / configure / maintain a MySQL database. But I plan to have this fixed within the next few weeks, and then we'll put out a bugfix release.

Of course, we'd also welcome pull requests from anyone who wants to fix this!

**Comment by AverytheFurry** [comment]
hm seems like I should get to using mysql then x3

**Comment by thebaer** [comment]
Sorry I couldn't get to this earlier. There's a fix open for it now!

**Comment by kadallah** [comment]
Hey @thebaer sorry if this is a silly question, but how would one go about installing the quick fix?
