### ISSUE TITLE
here is a guide for Chinese mandarin users 中文用户指南

### ISSUE THREAD

**Issue by jiangshanghan** [writefreely/writefreely#504]
this is a simple guide for those Chinese mandarin users who just new here and dont know what to do,how to start.
一个简单的说明书，希望对汉语用户有所帮助。

[5“自由地写”项目.pdf](https://github.com/writefreely/writefreely/files/7004378/5.pdf)
here is the file
这是pdf版的文件。如果需要检察更新，请前往我的博客查看系列博文。

**Comment by thebaer** [comment]
Thanks for sharing! I'll close this issue, but I think many people would appreciate it if you shared this [on our forum](https://discuss.write.as/), too!
