### ISSUE TITLE
Gopher server not accessible when writefreely is launched by systemd

### ISSUE THREAD

**Issue by sobodash** [writefreely/writefreely#510]
### Describe the bug
The gopher version of the blog is not accessible when writefreely is loaded from systemd. When ./writefreely is executed directly, the gopher server works fine.

I have already ensured there is not a firewall issue preventing port 70 access, but even working on the same local server the gopher server only appears to start when running the exe instead of running it from the systemd script.

I had considered it might be a config file issue and tried modifying the systemd ExecStart parameter to include the -c flag and path to the config.ini, but no change in behavior. The gopher server appears to start according to journalctl, but no attempts to access localhost on port 70 (or the IP, or the named server...) appear in the log.

> Sep 21 01:27:15 linux.6c17f8.com systemd[1]: Started WriteFreely Instance.
> Sep 21 01:27:15 linux.6c17f8.com writefreely[177772]: 2021/09/21 01:27:15 Starting WriteFreely 0.13.1...
> Sep 21 01:27:15 linux.6c17f8.com writefreely[177772]: 2021/09/21 01:27:15 Loading /opt/writefreely/mentalswarf.com/config.ini configuration...
> Sep 21 01:27:15 linux.6c17f8.com writefreely[177772]: 2021/09/21 01:27:15 Loading templates...
> Sep 21 01:27:15 linux.6c17f8.com writefreely[177772]: 2021/09/21 01:27:15 Loading pages...
> Sep 21 01:27:15 linux.6c17f8.com writefreely[177772]: 2021/09/21 01:27:15 Loading user pages...
> Sep 21 01:27:15 linux.6c17f8.com writefreely[177772]: 2021/09/21 01:27:15 Loading encryption keys...
> Sep 21 01:27:15 linux.6c17f8.com writefreely[177772]: 2021/09/21 01:27:15 Connecting to mysql database...
> Sep 21 01:27:15 linux.6c17f8.com writefreely[177772]: 2021/09/21 01:27:15 Adding {domain} routes (single user)...
> Sep 21 01:27:15 linux.6c17f8.com writefreely[177772]: 2021/09/21 01:27:15 Going to serve...
> Sep 21 01:27:15 linux.6c17f8.com writefreely[177772]: 2021/09/21 01:27:15 Serving on http://localhost:6060
> Sep 21 01:27:15 linux.6c17f8.com writefreely[177772]: 2021/09/21 01:27:15 ---
> Sep 21 01:27:15 linux.6c17f8.com writefreely[177772]: 2021/09/21 01:27:15 Serving on gopher://localhost:70

And confirmed again by attempting telnet to localhost:

> ┌─[root@linux] - [/opt/writefreely] - [2021-09-21 01:32:48]
> └─[0] <> telnet localhost 70
> Trying ::1...
> Trying 127.0.0.1...
> telnet: Unable to connect to remote host: Connection refused

When launching ./writefreely directly the result is:

> ┌─[root@linux] - [~] - [2021-09-21 01:35:05]
> └─[0] <> telnet localhost 70
> Trying ::1...
> Connected to localhost.
> Escape character is '^]'.

Ubuntu 20.04.3 LTS

### Steps to reproduce (if necessary)
1. Install writefreely
2. Add 'gopher_port = 70' to the [server] section of config.ini
3. Stop and start writefreely from systemd.
4. 'lynx gopher://localhost:70' fails to load the gopher server
5. Stop writefreely from systemd
6. Change to the writefreely directory and launch ./writefreely
7. 'lynx gopher://localhost:70' loads the gopher server

### Expected behavior
Gopher server should be launched as normal.

### Application configuration
 - **Single mode or Multi-user mode?**: Single
 - **Database?**: mysql
 - **Open registration?**: no
 - **Federation enabled?**: yes

**Version or last commit**: 0.13.1

**Comment by sobodash** [comment]
Further testing shows this problem is caused by the user that launches the writefreely process and not any part of writefreely itself.

Closing this issue since it is not relevant to the project.

**Comment by thebaer** [comment]
Thanks for reviewing and further testing this!

By "caused by the user", do you mean that the user launching the WriteFreely process needs to be privileged to run the Gopher server on a port lower than 1024? (I'm assuming this was the issue.)

If so, it might be worth keeping this issue open so we can fix the lack of error logging. I don't think we actually check for an error when starting the Gopher server.

**Comment by sobodash** [comment]
> By "caused by the user", do you mean that the user launching the WriteFreely process needs to be privileged to run the Gopher server on a port lower than 1024? (I'm assuming this was the issue.)

This may be the case. My temporary solution, probably ill-advised, was to just execute writefreely as root.

I used to run gophernicus, my prior gopher server, from a systemd script that executed it as 'nobody'. This worked and allowed port 70 access. I tried running writefreely as nobody but this did not solve the issue.

> If so, it might be worth keeping this issue open so we can fix the lack of error logging. I don't think we actually check for an error when starting the Gopher server.

Yeah. Error logging would help a lot in diagnosing what is going wrong here. I'm a big fan of gopher and writefreely's federation and ability to simultaneously server content over gopher is what got me to adopt the platform.

My systemd script is as follows:

> [Unit]
> Description=WriteFreely Instance
> After=syslog.target network.target mysql.service
> 
> [Service]
> Type=simple
> StandardOutput=syslog
> StandardError=syslog
> #User=writefreely
> #Group=writefreely
> WorkingDirectory=/opt/writefreely/mentalswarf.com
> ExecStart=/opt/writefreely/mentalswarf.com/writefreely
> Restart=always
> 
> [Install]
> WantedBy=multi-user.target

Uncomment the User and Group lines to get back to the state that is producing this error.

Just to verify proper firewall status:

> ┌─[root@linux] - [~] - [2021-09-21 08:10:16]
> └─[0] <> ufw status
> Status: active
> 
> To                         Action      From
> --                         ------      ----
> 22/tcp                     ALLOW       Anywhere
> Nginx Full                 ALLOW       Anywhere
> 70/tcp                     ALLOW       Anywhere
> 22/tcp (v6)                ALLOW       Anywhere (v6)
> Nginx Full (v6)            ALLOW       Anywhere (v6)
> 70/tcp (v6)                ALLOW       Anywhere (v6)

**Comment by sobodash** [comment]
A possible workaround to avoid running writefreely as root is to use CAP_NET_BIND_SERVICE present in Linux kernel 2.6.24+:

`setcap 'cap_net_bind_service=+ep' /opt/writefreely/writefreely`

This will allow a non-elevated user to bind to ports lower than 1024. The only issue is LD_LIBRARY_PATH becomes inaccessible. So far this does not appear to affect writefreely.
