### ISSUE TITLE
Data URLs are not rendert in images

### ISSUE THREAD

**Issue by sebastiansIT** [writefreely/writefreely#512]
### Describe the bug
If I use a data url to insert a image into an article, the image tag is rendert with an empty source. Inside of the editor the image is shown correctly.

### Steps to reproduce (if necessary)
1. Create a data URL from a picture (i.E. with https://dataurl.app)
2. Open a new Article in writefreely 
3. Click on 'Insert' then 'image' 
4. Insert this data URL into 'Image URL'
5. Press enter
6. Save the article and show it.

### Expected behavior
The rendert HTML-Element <img> contains the data url in the attribute "src".

### Application configuration
I don't host the instance blog.rollenspiel.monster, so I can't tell you.

**Version or last commit**:
I don't know but I think it's the latest one.

**Comment by SuaYoo** [comment]
FYI this is reproducible at the time of this comment on hosted write.as

**Comment by thebaer** [comment]
Also see our previous discussion on this: #80

**Comment by sebastiansIT** [comment]
Hi @thebaer, 

OK, the general aspects of this are discusses in #80 and the resulting problems for writers are also addressed by #517. So I mark this as a duplicate and close it.
