### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by JamieSlome** [writefreely/writefreely#522]
Hey there!

I belong to an open source security research community, and a member (@dwisiswant0) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by LennyPenny** [comment]
is this an sql injection? D:

**Comment by JamieSlome** [comment]
@LennyPenny - we cannot currently openly discuss the issue, but for other maintainers, the report can be viewed directly here:

https://huntr.dev/bounties/6a570cf6-b743-4662-a47f-c75d871bce69/

It is private and only accessible to maintainers with repository write permissions.
