### ISSUE TITLE
Questions about updating writefreely binary

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [writefreely/writefreely#527]
Hi,
I wanted to use writefreely docker image but sadly i had problems so now i use the binary (great work btw, thanks <3) and now i have 2 questions:
1. when there is new update do i need to delete all files (including db, static files) or do i just swap the binary with it's new version? (i know it sound dumb i just want to make sure) and if yes, would not my blogs get deleted too?
2. is there an easy way to update? i really do not want each day or week come here and look in releases to see if there is a new version or not so if there an automatic way to do it? i tried to use github https://github.com/writefreely/writefreely/releases/latest but i still keep failing to try and download files using wildcard

**Comment by EsmailELBoBDev2** [comment]
UPDATE: never mind about question number 2, i (startpaged) more and made a script, here if anyone else want to use it:
```
#!/bin/sh
killall writefreely
curl -s https://api.github.com/repos/writefreely/writefreely/releases/latest \
| grep "linux_amd64.tar.gz" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -O writefreely.tar.gz -qi -
tar --strip-components=1 -zxf writefreely.tar.gz
chmod +x writefreely
./writefreely 2>&1 1>/dev/null &
rm writefreely.tar.gz
```

but my num1 question still want to know if i replaced files with new update, my blogs will get deleted or nah

**Comment by thebaer** [comment]
Hey, thanks for taking an interest in the project! As we mention [on our site](https://writefreely.org/support), the issue tracker here is only meant for bug reports -- [our forum](https://discuss.write.as/c/development/7) is the right place to ask questions. If you could create this topic over there, it'd be much appreciated, and I'd be happy to help!

**Comment by EsmailELBoBDev2** [comment]
Okay, gotcha!
