### ISSUE TITLE
how to unpin?

### ISSUE THREAD

**Issue by cauerego** [writefreely/writefreely#535]
pin a post.

i can't find a way (in the web interface) to unpin.

can you help?

**Comment by thebaer** [comment]
As we mention at the top of our [contributing guide](https://github.com/writefreely/writefreely/blob/develop/CONTRIBUTING.md#contributing-to-writefreely), the GitHub issue tracker isn't for questions and help with the software. Please feel free to ask [on our forum](https://discuss.write.as)!

**Comment by cauerego** [comment]
i have used discussed extensively, and i still have too many accounts spread around. today i can't. it takes too long to load on my slow internet for whatever reason, i couldn't even open it to search through it.

but...

why do you tag this as "not a bug"?

**Comment by cauerego** [comment]
in fact, i tried it again and found a work-around which just confirms this as a bug:

https://discuss.write.as/t/unpinning-a-post/1773/3

even if it helps in my immediate use case, still clearly a coding bug.
