### ISSUE TITLE
Outdated docker-images posted on docker hub

### ISSUE THREAD

**Issue by davralin** [writefreely/writefreely#547]
### Describe the bug
The container-image on docker hub is 10 months old, and is pressumably severely out of date with regards to support libraries and general patch-management for the base-container-image.

Since this is a web-facing application, that should probably be remediated.

I propose a thing where the container-tag `latest` points to the latest development in the `develop`-branch, and release-tags are added as tagged here on github.

I wanted to propose this with a PR, but I couldn't find the relevant parts for how the images are put up on docker hub, can I assume that this process is manual, and/or depends on the, no longer free, auto-build on docker hub?

I'm prepared to fix some parts of this myself, as from other issues here, I see you claim to not be as familiar with container images - I need to know how to integrate with the current processes however.

**Comment by carbontwelve** [comment]
I was in the process of documenting how to deploy Writefreely with Dokku but the outdated docker hub images is a big blocker.

**Comment by thebaer** [comment]
It's manual, yes. Here's how the Docker image gets built when doing an official release: 

https://github.com/writefreely/writefreely/blob/46bb8e65a12cc697de7f9d5881e24146f519fcdd/Makefile#L62-L63

And then how it gets pushed:

https://github.com/writefreely/writefreely/blob/46bb8e65a12cc697de7f9d5881e24146f519fcdd/Makefile#L129-L130

I'm definitely out of my element here, so if there's a better / automated way to do this, I'm all ears!

**Comment by thebaer** [comment]
Also note this is related to #518.

**Comment by carbontwelve** [comment]
@thebaer GoToSocial have a drone config (https://github.com/superseriousbusiness/gotosocial/blob/main/.drone.yml) for pushing their releases to docker; I haven't used drone myself but it looks to be a self hosted github actions kind of thing.

**Comment by thebaer** [comment]
@carbontwelve Looks like that could be a good way to go! Happy to give access / make any changes needed on my end to make it possible.

**Comment by davralin** [comment]
I am more inclined to use GitHub-actions. I can generate a compatible drone-config for build/deploy of container images, if someone provides drone itself.

Thanks for the pointers, I'll see when I can have something ready for this.

**Comment by carbontwelve** [comment]
@davralin I agree, GitHub actions is available and is able to do the same job.

**Comment by stephane-klein** [comment]
@thebaer @davralin #553 is merged, but https://hub.docker.com/r/writeas/writefreely/tags contains always outdated *writefreely* version. Docker image are hosted in another repository? :thinking:

**Comment by davralin** [comment]
Check under `This PR does NOT:` on #553.

I don't really use writefreely anymore, so I don't have the bandwidth with helping any more here.

**Comment by strass** [comment]
Yeah it looks like the github action is setup to push to github's container repo `ghcr.io/writefreely/writefreely` not dockerhub. However, while it looks like the action succeeds there are some access issues: `https://ghcr.io/v2/writefreely/writefreely/manifests/latest` responds with `UNAUTHORIZED`
