### ISSUE TITLE
Serving ActivityPub objects

### ISSUE THREAD

**Issue by silverpill** [writefreely/writefreely#564]
### Describe the bug

According to [ActivityPub specification](https://www.w3.org/TR/activitypub/#retrieving-objects), servers should respond with ActivityStreams object representation to requests having `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` in Accept header, but apparently only `application/activity+json` is supported

>Servers ... MUST present the ActivityStreams object representation in response to application/ld+json; profile="https://www.w3.org/ns/activitystreams", and SHOULD also present the ActivityStreams representation in response to application/activity+json as well.

https://github.com/writefreely/writefreely/blob/b7f732b9154096d6864f2fa9469fe9c7a9b73d58/posts.go#L1123

### Steps to reproduce (if necessary)

```shell
curl -H 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' https://***/api/posts/***
```

The server returns the standard API response:

```json
{
  "code": 200,
  "data": {
    ...
  }
}
```

### Expected behavior

Server should return ActivityStreams object representation.

**Comment by thebaer** [comment]
Thanks for reporting this! Fixed now, and will go into v0.14.

**Comment by silverpill** [comment]
@thebaer I tried this:

```
curl -H 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' https://blog.writefreely.org/version-0-14
```

But it returns HTML, not JSON.

The header value in #766 seems to be correct though. Perhaps the change wasn't included in 0.14?

**Comment by thebaer** [comment]
Thanks for pointing that out! Looks like those previous changes only encompassed the API endpoints, and not the canonical / public URLs for blogs and posts. That's all fixed in #779.

**Comment by silverpill** [comment]
Thank you for looking into this!
Has this patch been applied to any live instance where I can test it?

**Comment by thebaer** [comment]
Yes, it's live on Write.as now!

**Comment by silverpill** [comment]
Everything working as expected. Thanks a lot

**Comment by thebaer** [comment]
Great, thank you for verifying!
