### ISSUE TITLE
Releasing new versions is blocked due to bug in other project?

### ISSUE THREAD

**Issue by davralin** [writefreely/writefreely#565]
So, I'm completely removing the issue-template here, as this is more of a overlay-bug/placeholder for [this thing](https://writing.exchange/@matt/108296096956116443) - or [this](https://github.com/writefreely/writefreely/discussions/550#discussioncomment-2812338) if you'd like.

As I understand it, there's a bug in [xgo](https://github.com/techknowlogick/xgo/issues/109) - which is blocking a release.

That bug has a workaround, which is building with go 1.15 (which I understand is EOL?) - but that workaround comes with [this](https://github.com/techknowlogick/xgo/issues/155) bug again - which makes the whole thing rather messy and convoluted.

I'm not a go-developer, nor do I think I'm going to start being one anytime soon - so "bugs that needs coding" isn't something I can help with - however, that last "bug" seems like it can be fixed by adding new root-CA's somewhere in a container.

Did you also notice [this](https://github.com/techknowlogick/xgo/issues/109#issuecomment-901601165), as a potential fix/workaround?

**Comment by thebaer** [comment]
Yes, I think if we can add that to the container, it should build fine. Also saw that comment, though I'm not sure what to do with it. Any ideas?
