### ISSUE TITLE
HTML Self-closing tags confuse the sanitizer and cause document to break [READ COMMENTS]   (Original issue title: Iframe allow tag is removed from article html) )

### ISSUE THREAD

**Issue by DRKSLV** [writefreely/writefreely#566]
### Describe the bug
I made a little [widget](https://lilguy.kartonrad.de/mirror/) specifically for embedding in a blog post.
Unfortunately, it requires camera access in order to be cool.
When i add the allow tag to my iframe as described in 
https://writefreely.org/docs/v0.13.1/writer/html#iframe
it is simply stripped from the output

i realize this might be for security reasons, but i feel that this is a little overprotective handholding when i'm running my own single-user instance... and misleading docs at the very least..

(also unrelated question but is it intended that only todays posts are displayed on my index page in everything but novel mode?!
there is like no way to access them otherwise?!
also i have lost the ability to pin posts, it returns a 404 error, despite no config change on my part?! 
sorry for these unrelated things but i have to ask them somewhere, i am having a bad time rn, prlly something on my part)

### Steps to reproduce (if necessary)
1. Go to New Post
2. Paste in example from the documentation
3. allow tag will be stripped

### Expected behavior
allow tag should not be stripped

### Application configuration
 - **Single mode** 
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: v0.13.1

**Comment by DRKSLV** [comment]
fun! the pin thing isn't even a reverse proxy issue, even though the request doesn't appear in logs?!
wieeerd and why did this start happening randomly?

**Comment by DRKSLV** [comment]
Examples::
![Screenshot 2022-06-09 171053](https://user-images.githubusercontent.com/56208328/172881976-0412ebbe-40d5-41b7-873d-a16f3266ede1.jpg)
![Screenshot 2022-06-09 171158](https://user-images.githubusercontent.com/56208328/172881756-98e5df1a-e988-4fcd-8675-9217bf56dcce.jpg)
65.jpg)

Reproduce issue with this piece of text
```
# breaks everything lmao 

<iframe src="https://lilguy.kartonrad.de/mirror" width="400" height="1000" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"/>
```

The response payload will contain invalid html, the closing tag after the iframe is destroyed and escaped by the sanitizer
![Screenshot 2022-06-09 171730](https://user-images.githubusercontent.com/56208328/172882982-1de0a200-78ce-46da-a1d7-4ead491bef15.jpg)

**Comment by thebaer** [comment]
Hi, can you clarify the exact bug / improvement you want to see here? This is a lot to consume :slightly_smiling_face:

**Comment by DRKSLV** [comment]
hold on i'll recreate the issue, if i can still reproduce it
