### ISSUE TITLE
Using MySQL driver without a password fails.

### ISSUE THREAD

**Issue by jakehamilton** [writefreely/writefreely#568]
### Describe the bug

Attempting to use the MySQL database driver without a password set causes
the program to throw an error and exit, printing the following.

```
Database user or password not set.
```

<details>
  <summary>View <code>config.ini</code> file.</summary>

```ini
[app]
host = http://local.test
site_name = WriteFreely
theme = write

[database]
database = writefreely
host = localhost
password = ""
port = 3306
tls = 
type = mysql
username = writefreely

[server]
autocert = 
bind = localhost
gopher_port = 0
keys_parent_dir = /var/lib/writefreely
pages_parent_dir = /nix/store/0sd080c203cc8nrgkmbjd8i5ydl4d2r5-source
port = 80
static_parent_dir = /nix/store/07va1db963wnsbm84lpxz3jcdjyxkkir-writefreely-assets-0.13.1
templates_parent_dir = /nix/store/0sd080c203cc8nrgkmbjd8i5ydl4d2r5-source
```

</details>

I'm currently trying to wire up a NixOS module for WriteFreely. NixOS's MySQL module
configures database users for auth with either [`unix_socket` or `auth_socket`](https://github.com/NixOS/nixpkgs/blob/ccf8bdf72624521358be6bb7d9b524c4cbcf7aff/nixos/modules/services/databases/mysql.nix#L470) and does not initialize users with a password.

### Steps to reproduce (if necessary)

1. Start MySQL.
2. Create a user with either `unix_socket` or `auth_socket` auth as described above.
3. Configure WriteFreely to use MySQL with an empty password entry.
4. Start WriteFreely.

### Expected behavior

WriteFreely _should_ be able to connect to the database without a password, though I'm not familiar enough with Go or the libraries underlying the database system to know if that's possible here (though my gut says it should be).

### Application configuration
 - **Single mode or Multi-user mode?** both
 - **Database?** [mysql/sqlite] mysql
 - **Open registration?** [yes/no] both
 - **Federation enabled?** [yes/no] both

**Version or last commit**: 0.13.1

**Comment by thebaer** [comment]
Thanks for reporting this! Fixed and will be in the next release.
