### ISSUE TITLE
Newline in MathJax

### ISSUE THREAD

**Issue by fedeb95** [writefreely/writefreely#575]
### Describe the bug
Adding a newline in MathJax with \\ doesn't work

### Steps to reproduce (if necessary)
1. Create a blog post with MathJax and a newline sequence \\
2. Publish post

### Expected behavior
A newline should have been inserted in correspondence of the \\ sequence

### Application configuration
I don't know, it's noblogo.org

**Version or last commit**:
I don't know

**Comment by thebaer** [comment]
Hm, I'm not sure I understand what you mean. Can you share the exact text you're using in your post?

**Comment by fedeb95** [comment]
I'm not able to replicate this exactly anymore so I think it can be closed. However I remember not being able to find a way to write an equation on multiple lines. I had the same problem in pure MathJax on my website which I solved with:

$$
\begin{align}
... \\
... \\
\end{align}
$$

which doesn't seem to work in writefreely.

**Comment by thebaer** [comment]
I'll close this for now, but if you find the text that can reproduce this bug please feel free to re-open.
