### ISSUE TITLE
http 500 returned if blog description is too long for a mysql database

### ISSUE THREAD

**Issue by Flameborn** [writefreely/writefreely#600]
### Describe the bug

If MySQL is used as the database engine, the blog description field is limited to 160 characters. When this limit is reached at /me/c/blogname, and the form is submitted via the *Save* button, a HTTP 500 error is returned.

Although I haven't tested it, but this is likely the case for the blog title as well (255 characters).

### Expected behavior

The user should be informed upon reaching the limit, preferably before submitting the form.

### Application configuration

**Version or last commit**: 29c898867ac23ea0df794ac481b1c8b8522d6c84

**Comment by thebaer** [comment]
Hi, can you please share the server logs from around when you encounter the 500 error, so we can figure out what's going on?

**Comment by Flameborn** [comment]
Hello,

Sorry, I forgot to include the two received errors. These are after a post request to */api/collections/username*:

```
ERROR: 2022/11/19 22:27:46 database.go:939: Unable to update collection: Error 1406: Data too long for column 'description' at row 1
ERROR: 2022/11/19 22:27:46 collections.go:1087: Couldn't update collection
```

**Comment by thebaer** [comment]
Thanks. And what version of MySQL are you running?

**Comment by Flameborn** [comment]
I'm running Percona Server 8.0.29_21, which is a drop-in replacement for MariaDB and MySQL.

**Comment by thebaer** [comment]
Thanks again, this will be fixed in the next release!

**Comment by Flameborn** [comment]
Thank you.
