### ISSUE TITLE
Editor Screen Doesn't Support Bidirectional Texts

### ISSUE THREAD

**Issue by UsernamesAreFuckedUp** [writefreely/writefreely#612]
### Describe the bug
When I'm writing in an RTL language at the editor screen, text direction is not set to RTL. But it has no problems with LTR languages. In other words, the user is expecting the text field to support bidirectional texts, but it doesn't. 

### Steps to reproduce (if necessary)
1. Go to the editor screen
2. Start typing in an RTL language (Persian, Arabic, etc.), followed by some LTR Paragraph.
3. You'll see something like this, which is disturbing.
![image](https://user-images.githubusercontent.com/96365880/209567446-fe6b0612-657f-4a63-9195-987db399cbe2.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/96365880/209567203-f888bcc3-19e7-406f-849e-7c0a98615070.png)
Adding bidi support is very easy, I assume. I just attached `dir="auto"` to the `textarea`. (Maybe there are some other places you should use this attribute. I don't know.)

### Applications configuration
 - Multi-user Mode
 - Open Registration
 - Federation Enabled

v0.13.1

**Comment by thebaer** [comment]
Thanks, that fix should be easy enough! Anyone should feel free to tackle this. Otherwise I'll get to it when I can.
