### ISSUE TITLE
Cross compilation fails

### ISSUE THREAD

**Issue by GSI** [writefreely/writefreely#636]
Tested on a Linux amd64 host all attempted cross-compile commands result in the error outlined beneath.

### Attempts

`$ env GOOS=linux GOARCH=386 go build -v -tags='sqlite' ./cmd/writefreely/`
`$ env GOOS=windows GOARCH=amd64 go build -v -tags='sqlite' ./cmd/writefreely/`
`$ env GOOS=openbsd GOARCH=amd64 go build -v -tags='sqlite' ./cmd/writefreely/`
`$ env GOOS=android GOARCH=arm64 go build -v -tags='sqlite' ./cmd/writefreely/`

### Error

```
...
github.com/writefreely/writefreely
# github.com/writefreely/writefreely
./database-sqlite.go:39:30: undefined: sqlite3.Error
./database-sqlite.go:40:31: undefined: sqlite3.ErrConstraint
```

Interestingly, openbsd/arm64 fails, but when run from an actual OpenBSD/arm64 system, the build completes successfully.

As one may expect, when `-tags='sqlite'` is omitted, cross-builds do work.

Normal builds compile just fine (`go build -v -tags='sqlite' ./cmd/writefreely/`).

**Version or last commit**:
0.13.2

**Comment by thebaer** [comment]
This should be covered in the Makefile, e.g. `make build-windows`. I'd say for other combinations, we should update the [documentation](https://github.com/writefreely/documentation) to explain how to compile.

Closing this since I don't think it's a bug, but let me know if you think otherwise.
