### ISSUE TITLE
Fonts are not applied on first load

### ISSUE THREAD

**Issue by Alex0007** [writefreely/writefreely#650]
### Describe the bug
Fonts are only applied on second load

### Steps to reproduce (if necessary)
1. Go to example post https://nouni.sh/alex0007/unsighted-review
2. Look at incorrect fonts
3. Refresh page
4. Fonts are now correct

First load:
<img width="146" alt="Screenshot 2023-02-27 at 22 56 45" src="https://user-images.githubusercontent.com/1143226/221657017-83410048-da14-4bcb-b213-6c8b545c77e6.png">

Second load:
<img width="152" alt="Screenshot 2023-02-27 at 22 56 50" src="https://user-images.githubusercontent.com/1143226/221657025-88a095dc-9e04-4b6b-969d-04d45ab41541.png">

Instance version: 0.13.1

**Comment by thebaer** [comment]
I believe this will only happen if you're on a slow internet connection... if the fonts fail to load quickly, the browser falls back to default ones, so readers aren't waiting forever to read the actual content. And once the fonts _do_ download, any posts you view from then on should show up correctly.

I think this is the best we can do in this situation, so I'm going to close this as a not-a-bug. But please feel free to continue discussing.

**Comment by Alex0007** [comment]
My internet is 100mbps, i asked my girlfriend to reproduce this – she had the same result

**Comment by Alex0007** [comment]
<img width="1190" alt="Screenshot 2023-02-28 at 17 34 54" src="https://user-images.githubusercontent.com/1143226/221869493-6f59d880-5adb-4080-82b8-c2ec0686b2f7.png">

@thebaer this bug is 100% reproducible, for example with online web-page screenshot tool. Fonts are incorrect

**Comment by Alex0007** [comment]
**Font swap period**

If the font face is not loaded, any element attempting to use it must render a fallback font face. If the font face successfully loads during this period, it is used normally. Font failure period. If the font face is not loaded, the user agent treats it as a failed load causing normal font fallback.


```css
font-display: optional;
```

Gives the font face an extremely small block period and _no swap period_.
