### ISSUE TITLE
Gopher can't access anything but main menu, binds to "gopher://localhost:70"

### ISSUE THREAD

**Issue by Moonbase59** [writefreely/writefreely#665]
### Describe the bug
I have used `sudo setcap 'cap_net_bind_service=+ep' /var/www/writefreely/writefreely` so writefreely will bind to priviledged ports. In `config.ini`, I set `gopher_port = 70`.

The logs tell me `Serving on gopher://localhost:70`.

I can actually use `lynx gopher://localhost:70/` or `lynx gopher://blog` in my local net and it shows me the main menu (3 blogs) but whenever I try to access one of these, it tells me `Alert! Unable to access document`.

I wonder if this might be due to the "localhost" or a bad bind. I remember I _had_ to set the HTTP bind to `0.0.0.0` before it worked okay to the net. I tried adding a `gopher_bind = 0.0.0.0` but that of course didn’t work out.

### Steps to reproduce (if necessary)
1. Use a multiuser writefreely, enable gopher.
2. Use lynx to access the main menu and one of the blogs.
3. Error.

### Expected behavior
It should have correctly shown the blog.

### Application configuration
 - **Multi-user mode** 
 - **Database?** mysql
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: 0.13.2

**Comment by thebaer** [comment]
Hi, can you share the application logs from around when you try to access any blog posts via gopher?

**Comment by Moonbase59** [comment]
Sure, here goes (from journalctl, hope these are the right ones):

```log
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 Starting WriteFreely 0.13.2...
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 Loading config.ini configuration...
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 Loading templates...
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 Loading pages...
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 Loading user pages...
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 Loading encryption keys...
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 Connecting to mysql database...
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 Initializing local timeline...
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 Adding blog.syvi.net routes (multi-user)...
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 Going to serve...
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 Serving on http://0.0.0.0:80
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 ---
Mar 27 17:34:49 blog writefreely[2972]: 2023/03/27 17:34:49 Serving on gopher://localhost:70
Mar 27 17:37:00 blog writefreely[2972]: 2023/03/27 17:37:00 [READ] Updating post cache
Mar 27 17:37:00 blog writefreely[2972]: 2023/03/27 17:37:00 "GET /read/feed/" 200 37.315707ms "NextCloud-News/1.0"
Mar 27 17:37:00 blog writefreely[2972]: 2023/03/27 17:37:00 [READ] Updating post cache
Mar 27 17:37:00 blog writefreely[2972]: 2023/03/27 17:37:00 "GET /read/feed/" 200 34.291637ms "NextCloud-News/1.0"
Mar 27 17:37:42 blog writefreely[2972]: 2023/03/27 17:37:42 gopher: /
Mar 27 17:38:10 blog writefreely[2972]: 2023/03/27 17:38:10 gopher: /
Mar 27 17:46:36 blog writefreely[2972]: 2023/03/27 17:46:36 gopher: /
Mar 27 17:47:06 blog writefreely[2972]: 2023/03/27 17:47:06 gopher: /
Mar 27 17:58:32 blog writefreely[2972]: 2023/03/27 17:58:32 gopher: /
Mar 27 18:09:30 blog writefreely[2972]: 2023/03/27 18:09:30 [READ] Updating post cache
Mar 27 18:09:30 blog writefreely[2972]: 2023/03/27 18:09:30 "GET /" 200 29.22013ms "Lynx/2.9.0dev.10 libwww-FM/2.14 SSL-MM/1.4.1 GNUTLS/3.7.1"
Mar 27 18:11:35 blog writefreely[2972]: 2023/03/27 18:11:35 "GET /about" 200 1.777802ms "Lynx/2.9.0dev.10 libwww-FM/2.14 SSL-MM/1.4.1 GNUTLS/3.7.1"
Mar 27 18:15:29 blog writefreely[2972]: 2023/03/27 18:15:29 "GET /" 200 2.144029ms "Lynx/2.9.0dev.10 libwww-FM/2.14 SSL-MM/1.4.1 GNUTLS/3.7.1"
Mar 27 18:16:23 blog writefreely[2972]: 2023/03/27 18:16:23 gopher: /
Mar 27 18:16:43 blog writefreely[2972]: 2023/03/27 18:16:43 gopher: /
Mar 27 18:21:19 blog writefreely[2972]: 2023/03/27 18:21:19 Shutting down...
Mar 27 18:21:19 blog writefreely[2972]: 2023/03/27 18:21:19 Closing database connection...
Mar 27 18:21:19 blog writefreely[2972]: 2023/03/27 18:21:19 Done.
```

**Comment by Moonbase59** [comment]
Further investigations (using netcat on port 70) seem to indicate that my routing setup is okay (public domain, port 70 forwarding in my router to NGINX proxy manager, NGINX forwarding a TCP "stream" on port 70 to the local writefreely VM) BUT … I somehow feel the NGINX doesn’t bind to port 70. Hm. Have you by chance any experience with NGINX Proxy Manager forwarding priviledged ports?

My tests so far:
- Use `sudo nc blog 70` on a local machine, and `sudo nc -l 70` on the blog VM (having writefreely shut down) → works
- Use `sudo nc blog.syvi.net 70` on local machine, `sudo nc -l 70` on proxy → works but suspect: nc should complain that port 70 is in use if NGINX Proxy Manager would have bound correctly. Hm. At least "outside" routing an forwarding through the router okay.
- I somehow suspect you might be using my real blog address (blog.syvi.net) but with port 70, so it _might_ be a binding priviledged port thing on NGINX Proxy Manager… Any idea how to further diagnose this and make sure your part works alright?

**Comment by Moonbase59** [comment]
Darn me! I’ve been a complete idiot and forgot to add a '70:70' port mapping in the `docker-compose.override.yml` for my NGINX Proxy Manager. It _can_ actually bind correctly to port 70 (hooray!) but if one doesn’t expose the port outside the docker container it’ll _of course_ never work!

Sorry for stealing your time, but your prompt reaction and willingness to help are much appreciated nevertheless! Keep up the good work!

Above addresses should (hopefully) now both work.

**Comment by Moonbase59** [comment]
Closing this as done.
