### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by RRD-FelixLi** [writefreely/writefreely#677]
I can't login the website. 
The home of website and the error description show as below:
![Server error](https://user-images.githubusercontent.com/131743457/234198831-7c75839c-9ef7-4bd0-ac77-e97ab03f66ad.PNG)

**Comment by RRD-FelixLi** [comment]
Thanks.
But why I was navigated here? If the paper.wf website is not control by you, how about the writefreely?
What's the relationship between the paper.wf website and the writefreely?
![Capture](https://user-images.githubusercontent.com/131743457/234243165-f5867364-c8a5-4a04-83df-9d6ce82a91c1.PNG)

**Comment by RRD-FelixLi** [comment]
I got it, thanks.

**Comment by pylapp** [comment]
Back to normal situation.

Could be nice to have better error messages and a kid of UI to contact instance admins.

Could be closed.
