### ISSUE TITLE
Server error on paper.wf

### ISSUE THREAD

**Issue by pylapp** [writefreely/writefreely#683]
### Describe the bug
Error 500 while trying to get paper.wf pages

### Steps to reproduce (if necessary)
1. Go to any page of paper.wf
2. Enjoy...

### Expected behavior
Display the normal pages 

### Application configuration
 - web site 
 - bug defined here as asked in the error page of the website

![image](https://user-images.githubusercontent.com/7559007/234408511-886e52ab-cc41-4d8c-b094-13e980cfa639.jpeg)

**Comment by thebaer** [comment]
Sorry for the confusing error message, but please check other issues here before opening new ones. See #678.

**Comment by pylapp** [comment]
Back to normal situation.

@thebaer Could be nice to have better error messages and a kind of UI to contact instance admins.

Could be closed.
