### ISSUE TITLE
writefreely.el : <!--more--> for excerpts gets converted to <!&#x2013;more&#x2013;>

### ISSUE THREAD

**Issue by adcl-0** [writefreely/writefreely#685]
### I am using emacs org mode with WriteFreely.el
when I insert `<!--more-->` in a blogpost, after export and publish to blog it gets converted to `<!&#x2013;more&#x2013;>`

### Application configuration
 - **Single mode** 
 - **Database?** [sqlite]
 - **Open registration?** [no]
 - **Federation enabled?** [yes]

**Version or last commit**: version : 0.13.2 _ amd64

**Comment by thebaer** [comment]
This kind of issue usually has to do with the client or input method, not the application itself. So this is probably an issue for the [writefreely.el](https://github.com/dangom/writefreely.el) library.

**Comment by thebaer** [comment]
Issue with the client library is here: dangom/writefreely.el#28
