### ISSUE TITLE
Cannot signup

### ISSUE THREAD

**Issue by Kiwi12135** [writefreely/writefreely#686]

**Comment by pylapp** [comment]
paper.wf instance is not related to this project authors.

Yes the error page of paper.wf points to that repository, but the developers here are not related to paper.wf instance ; they just provide the source code.

See #684 for more details.

**Comment by pylapp** [comment]
Back to normal situation.

Could be nice to have better error messages and a kid of UI to contact instance admins.

Could be closed.

**Comment by thebaer** [comment]
Thanks @pylapp, closing now.
