### ISSUE TITLE
open my account

### ISSUE THREAD

**Issue by marymetz46** [writefreely/writefreely#687]
how can i sign up

**Comment by pylapp** [comment]
paper.wf instance is not related to this project authors.

Yes the error page of paper.wf points to that repository, but the developers here are not related to paper.wf instance ; they just provide the source code.

See #684 for more details.

**Comment by pylapp** [comment]
Back to normal situation.

Could be nice to have better error messages and a kid of UI to contact instance admins.

Could be closed.
