### ISSUE TITLE
Federation: Not possible to accept subscription request / susbcribe from Mastodon

### ISSUE THREAD

**Issue by pylapp** [writefreely/writefreely#699]
### Describe the bug
As a user of _Write Freely_ in **write.as** instance I want to know how to accept subscription requests or disable such validation from fediverse, so that people can follow my account through Mastodon.

### Expected behavior

From Mastodon (some account), I expected to follow directly the account on write.as, but it seems there is some validation step to process in write.as side to accept the subscription request. Why such validation? Why cannot users in fediverse (Mastodon) just follow the account without validation? How validate requests?

### Application configuration
 - Federation enabled
 - write.as instance
 - Tried to follow so @pylapp@write.as with @pylapp@framapiaf.org

### Screen capture

<img width="573" alt="request to follow" src="https://github.com/writefreely/writefreely/assets/7559007/59242b24-0e50-4552-9e61-e294c67e30c3">

**Comment by anhgelus** [comment]
I have the same issue with a [self-hosted blog](https://blog.anhgelus.world).
