### ISSUE TITLE
CustomCSS is dereferenced but not found

### ISSUE THREAD

**Issue by RapidRotator** [writefreely/writefreely#701]
When using the default templates, `CustomCSS` is dereferenced but not found in several files. Requests fail after these log messages:

```
ERROR: 2023/05/27 09:35:27 collections.go:873: Unable to render collection index: template: collection.tmpl:9:7: executing "collection" at <.CustomCSS>: can't evaluate field CustomCSS in type writefreely.CollectionPage
ERROR: 2023/05/27 09:35:27 handle.go:533: [Web handler] 500: template: collection.tmpl:9:7: executing "collection" at <.CustomCSS>: can't evaluate field CustomCSS in type writefreely.CollectionPage
2023/05/27 09:35:27 Web internal error render
```

1. Start writefreely using a configuration where `templates_parent_dir` points to a folder with the unchanged templates directory as cloned from this repository.
2. Point a web browser to the instance

### Expected behavior
The templates to be rendered

### Application configuration
 - **Single mode
 - **mysql
 - **Open registration?** [no]
 - **Federation enabled?** [yes]

**Version or last commit**:
0.13.2

**Comment by thebaer** [comment]
Thanks for reporting this. Not sure how it got in there, but it should already be fixed with #533 -- so should work fine with the next release.
