### ISSUE TITLE
Failed to Sign-up through paper.wf

### ISSUE THREAD

**Issue by t0fr** [writefreely/writefreely#732]
Tried signing up and was presented with generic error message:

> Server error 😵
> 
> Please [contact the human authors](https://github.com/writefreely/writefreely/issues/new) of this software and remind them of their many shortcomings.
> 
> Be gentle, though. They are fragile mortal beings.
> 
> Also, unlike the AI that will soon replace them, you will need to include an error log from the server in your report. (Utterly primitive, we know.)
> 
> – Paper.wf 🤖

**Comment by thebaer** [comment]
Sorry for the confusing error message, but this is an issue with the paper.wf server, not the software. It seems to happen on occasion -- see #684. Would recommend retrying or finding a more reliable server to sign up on.
