### ISSUE TITLE
Rendering a blog is slow for giant databases

### ISSUE THREAD

**Issue by thebaer** [writefreely/writefreely#741]
### Describe the bug
On our Write.as instance, our `posts` table has over 4.25 million rows. For an individual blog with 9,000+ posts, rendering the blog index page is taking a long time (4 seconds or more), especially under general heavy load from other users on the platform.

### Steps to reproduce (if necessary)
1. Have 4.25M posts in system, with 9,000 belonging to one collection / blog
2. Make at least 50 requests / second to random, unrelated posts on the platform
3. Navigate to the blog with 9,000 posts
4. Notice extremely long load time

### Expected behavior
Blog should load in a reasonable time (under 2 seconds?)

### Application configuration
 - **Single mode or Multi-user mode?** multi-user
 - **Database?** mysql
 - **Open registration?** yes
 - **Federation enabled?** yes

**Version or last commit**: v0.13.2 (custom)

**Comment by thebaer** [comment]
I've added some time logging around the major queries in [handleViewCollection()](https://github.com/writefreely/writefreely/blob/65ec6b44e1bb11d7a40b30c5829afea7a9eabacd/collections.go#L789) and got this output:

```
after processCollectionPermissions: 1.164132206s
after GetPostsCount: 726ms
after IsCollectionAttributeOn: 922µs
after newDisplayCollection: 727ms
after nil owner, GetUserByID: 633µs
after GetPosts: 5.261454609s
after GetPinnedPosts: 79ms
after GetCollectionAttribute: 765µs
```

So I think the `GetPosts` query is causing the biggest issue, which comes out to this:

```sql
SELECT id, slug, text_appearance, language, rtl, privacy, owner_id, collection_id, pinned_position, created, updated, view_count, title, content
FROM posts
WHERE collection_id = 1
  AND pinned_position IS NULL
  AND created <= NOW()
ORDER BY created DESC
LIMIT 0, 10
```

When I run that with `EXPLAIN`, I get this:

```
+------+-------------+-------+-------+---------------+---------+---------+------+-------+----------------------------------------------------+
| id   | select_type | table | type  | possible_keys | key     | key_len | ref  | rows  | Extra                                              |
+------+-------------+-------+-------+---------------+---------+---------+------+-------+----------------------------------------------------+
|    1 | SIMPLE      | posts | range | id_slug       | id_slug | 5       | NULL | 18602 | Using index condition; Using where; Using filesort |
+------+-------------+-------+-------+---------------+---------+---------+------+-------+----------------------------------------------------+
```

Would something like this work, adding an index on all columns in this query?

```
CREATE INDEX posts_get_collection_index
    ON posts (collection_id ASC, pinned_position ASC, created DESC, id ASC);
```

**Comment by sgrigson** [comment]
I don't think you need the id column in the index, but the rest of the index seems reasonable.

None of the WHERE fields are in an index so that's definitely a red flag.

Worth applying the index, re-running the EXPLAIN, and seeing what comes up this time.

**Comment by UnderpantsGnome** [comment]
```sql
CREATE INDEX posts_get_collection_index
  ON posts (`collection_id`, `pinned_position`, `created`);
```

then the `possible_keys` in the explain output should be `posts_get_collection_index`

**Comment by UnderpantsGnome** [comment]
I would also suggest using [this tool](https://shlomi-noach.github.io/openarkkit/oak-online-alter-table.html) for the schema change, otherwise your app isn't going to be happy for a while as it runs,

**Comment by thebaer** [comment]
Okay, so I created the index without the `id` column and it seems to be using it fine:

```
+------+-------------+-------+-------+------------------------------------+----------------------------+---------+-------------+----------------------+
| id   | select_type | table | type  | possible_keys                      | key                        | key_len | ref         | rows  | Extra        |
+------+-------------+-------+-------+------------------------------------+----------------------------+---------+-------------+----------------------+
|    1 | SIMPLE      | posts | ref   | id_slug,posts_get_collection_index | posts_get_collection_index | 7       | const,const | 18602 | Using where  |
+------+-------------+-------+-------+------------------------------------+----------------------------+---------+-------------+----------------------+
```

That query is now taking ~600ms on its first run. Going to let that sit for a while and see how it does.

**Comment by gnomon-** [comment]
_Nice_.  Is a 600ms performance expectation for this query sufficient to yield the user experience you're after?

Also, is a similar indexing change worth considering for the sqlite schema as well, or did it not manifest this particular speed issue?

**Comment by thebaer** [comment]
It's good enough for now. Combined with Varnish on the frontend, it should only affect a few people -- my main priority was just getting it to load once within a reasonable timeframe.

I haven't tested with sqlite since it's not what we're using on our instance... But I don't see why we shouldn't also add it there, for parity and just in case the same issue arises.
