### ISSUE TITLE
ghcr.io Package Visibility

### ISSUE THREAD

**Issue by lstellway** [writefreely/writefreely#751]
### Describe the bug

I see a [build action](https://github.com/writefreely/writefreely/blob/65ec6b44e1bb11d7a40b30c5829afea7a9eabacd/.github/workflows/docker-publish.yml#L22) is configured for this repository.
I also see recent [successful build pipelines](https://github.com/writefreely/writefreely/actions/workflows/docker-publish.yml). 

When trying to pull the image _(while logged into the `ghcr.io` repository)_:
```sh
docker pull ghcr.io/writefreely/writefreely:latest
```

I receive an error:

> _Error response from daemon: denied_

Is it possible the [package visibility](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility) is not set to public?

**Comment by thebaer** [comment]
Thanks for mentioning this -- I've just set the package to Public (I think). Please let me know if you still have trouble with it!

**Comment by lstellway** [comment]
That took care of it! 
Thanks for the quick response 🙏 

You found a cool niche and look to have a fun set of projects - looking forward to playing with them 🍻
