### ISSUE TITLE
personaljournal.ca server error

### ISSUE THREAD

**Issue by boyawang-github** [writefreely/writefreely#755]
![image](https://github.com/writefreely/writefreely/assets/15026989/7666e5ee-0516-409c-9d17-44b7f1fe01ac)

The server for https://personaljournal.ca/ seems to be down. I got this message saying "Please [contact the human authors](https://github.com/writefreely/writefreely/issues/new) of this software and remind them of their many shortcomings."

Can someone please help? I am very worried about all my posts on this server and I don't have any backups.

**Comment by thebaer** [comment]
Hi, unfortunately we don't run this instance, so we can't do anything about it. The error message here is misleading (see #684) -- it'd be best to try and get in contact with the owner of this instance, if possible.
