### ISSUE TITLE
Image (and pinned post) links are malformed on second page of index

### ISSUE THREAD

**Issue by KGOrphanides** [writefreely/writefreely#762]
### Describe the bug
Explain what the bug is, in as much detail as possible...

### Steps to reproduce (if necessary)
1. Go to main page of blog (configured in notebook more in this page)
2. Click on '⇠ Older' to get to second page of index
3. note that you are now on /page/2
4. Observe that images within entries are broken because /page/ is now inserted into the URL in front of the image path. for example, where a /images/mundaun/mundaun1.jpeg (pointing at the image directory that lives on my nginx proxy server) now points to page/images/mundaun/mundaun1.jpeg

### Expected behavior
Image paths should remain as entered in the post.

Workaround: use full path to image including URL. 

The fact that there is a fairly easy workaround means that this is a low-priority issue in terms of solving this particular error, but points to other issues. For example, after a bit of poking, I've similarly found that pinned posts 404 if you're not on the root domain page (for example on /page/2 of the post listing).

### Application configuration
 - **Single mode** 
 - **Database?** [sqlite]
 - **Open registration?** [no]
 - **Federation enabled?** [yes]

**Version or last commit**:
0.13.2

**Comment by thebaer** [comment]
Can you please share a URL or the exact Markdown of a post where this is happening, so I can try to replicate it?

**Comment by KGOrphanides** [comment]
Apologies, I fixed the site as described, and I've not been able to replicate the issue by editing the links in the way I mentioned.

That was weird.
I'll re-open the ticket if I work out how to make it break again.
