### ISSUE TITLE
Dark mode does not render correctly for code blocks

### ISSUE THREAD

**Issue by MiguelGuthridge** [writefreely/writefreely#780]
### Describe the bug
After updating Writefreely to 0.14.0, I noticed that my blog site now renders in dark mode (likely respecting my browser's preference). However, code blocks and inline code snippets continue to render in light mode, which looks ugly and is frustrating to read.

Here is a screenshot from my blog that demonstrates the issue:
![image](https://github.com/writefreely/writefreely/assets/31365175/11a6916a-3c04-455a-9f9e-b67280462a6d)
[link to view the post](https://blog.miguelguthridge.com/representing-gender-programmatically)

### Steps to reproduce (if necessary)
1. Create a blog post that contains `inline code` and

```py
# Markdown code snippets

def hello(name):
    print(f"Hi, {name}")
```

2. Publish the blog post
3. Set your web browser to dark mode
4. View the published post

### Expected behavior
The code snippets render in a style consistent with the website theme.

### Application configuration
 - **Single mode or Multi-user mode?** single
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: v0.14.0

As a side note, is it possible for me to entirely disable dark mode support until this is fixed? How should I go about doing so?

**Comment by thebaer** [comment]
This was actually caused by a bad build that got sent out initially with v0.14. It included a custom stylesheet at `./static/local/custom.css` that you can safely delete. Once you do, that should fix this! But let me know if not.

**Comment by MiguelGuthridge** [comment]
Can confirm that doing so fixed it, although unfortunately that means no more dark mode. Maybe I'll try my hand at my own custom CSS for it :)
