### ISSUE TITLE
Server error when accessing tags page

### ISSUE THREAD

**Issue by blujan** [writefreely/writefreely#783]
### Describe the bug
I'm running Writefreely in a container with sqlite as DB, and I've come across what I think is a minor bug in the database API. When trying to access the page for tags (\<site\>/tag:\<tag\>), the server error page comes up instead of the list of posts with the tag as it should. Dropping into the logs I see the following error - 

```
2023-10-05 22:08:32 ERROR: 2023/10/06 05:08:32 database.go:1260: Failed selecting tagged posts: no such function: NOW
```

### Steps to reproduce (if necessary)
1. Setup a new instance using sqlite as backend
2. Create and publish a post containing a tag
3. Log out
4. Click on the tag link from within the post, i.e., \<uri\>/tag:\<tag\>

### Expected behavior
What should've happened? Page showing posts containing the given tag

### Application configuration
 - **Single mode** 
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** no

**Version or last commit**: 0.14.0

**Comment by blujan** [comment]
So dipping into the code, I do see the following at database.go:GetAllPostsTaggedIDs() - 

```
	if !includeFuture {
		timeCondition = "AND created <= NOW()"
	}
```

Should it be calling the helper function db.now() instead since I don't see the sqlite check after this bit modifying this string? If I get some time, I'll try this out to see if it changes the behavior of the above issue.

**Comment by thebaer** [comment]
Thanks for reporting this! Yes it should be calling `db.now()` here, instead. We'll gladly accept a PR if you do get around to fixing this!
