### ISSUE TITLE
Web internal error render

### ISSUE THREAD

**Issue by zer-far** [writefreely/writefreely#786]
### Describe the bug
When requesting [rant.li/nisemikol](https://rant.li/nisemikol/), I get a server error.

### Logs:
```
ERROR: 2023/10/08 18:47:18 collections.go:932: Unable to render collection index: template: collection.tmpl:12:61: executing "collection" at <.NextPageURL>: wrong number of args for NextPageURL: want 4 got 3
ERROR: 2023/10/08 18:47:18 handle.go:539: [Web handler] 500: template: collection.tmpl:12:61: executing "collection" at <.NextPageURL>: wrong number of args for NextPageURL: want 4 got 3
2023/10/08 18:47:18 Web internal error render
2023/10/08 18:47:18 "GET /nisemikol/" 500 2.0983076s "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0"
2023/10/08 18:47:18 http: superfluous response.WriteHeader call from github.com/writeas/impart.writeBody (response.go:31)
```

### Steps to reproduce (if necessary)
1. Go to [rant.li/nisemikol](https://rant.li/nisemikol/).

### Expected behavior
The blog should be displayed.

### Application configuration
 - **Single mode or Multi-user mode?** Multi-user mode
 - **Database?** [mysql/sqlite] mysql
 - **Open registration?** [yes/no] yes
 - **Federation enabled?** [yes/no] yes

**Version or last commit**:
v0.14.0

**Comment by thebaer** [comment]
Hmm, assuming you upgraded from a previous version, did you also replace the `templates/` directory with the latest files for v0.14?

**Comment by zer-far** [comment]
The blog works now after replacing templates/ directory with the latest one.
