### ISSUE TITLE
Custom CSS Not Working

### ISSUE THREAD

**Issue by nephatrine** [writefreely/writefreely#792]
### Describe the bug

I just updated to v0.14.0 from v0.13.2. I did the db migration seemingly without issue. I put my custom css in `[static_parent_dir]/static/local/custom.css` expecting it to "just work" as the documentation made that out to be the case... but it's not working. The file is there. I can access it by url at `[mysite]/local/custom.css` so write-freely must see it there is its serving it up and I see that reflected in the logs as well:

```
2023/10/13 14:02:05 "GET /local/custom.css" 200 146.344µs "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
```

When I inspect the source, it isn't adding a style line for it. Looking at the templates, CustomCSS must not being set properly.

I think the issue is that it isn't taking my `static_parent_dir` from the ini into account when checks CustomCSS - it's just checking from the current directory. If I create a bogus empty static/local/custom.css from the cwd path where I execute write-freely, it sets CustomCSS properly even though this isn't the static directory it uses for its actual operation and that isn't the file it actually serves.

### Expected behavior
It should recognize the local/custom.css in the static directory I specified in the configuration file.

### Application configuration
 - **Single mode or Multi-user mode?** Multi-User
 - **Database?** sqlite
 - **Open registration?** yes
 - **Federation enabled?** yes

**Version or last commit**: v0.14.0

**Comment by thebaer** [comment]
Thanks for reporting this! Just need to take that config value into account when loading the stylesheet.
