### ISSUE TITLE
Argh! Update from 0.13.2 to 0.14.0 made everything "dark mode"—how to get back to beautiful black-on-white text?!

### ISSUE THREAD

**Issue by Moonbase59** [writefreely/writefreely#798]
### Describe the bug
After updating to 0.14.0 (from 0.13.2) all my admin & blog pages are now in "dark mode".

_Personal opinion:_ I **hate, hate, hate** this un-ergonomic, un-readable, bad-for-the-eyes dark-mode hype! Text has to be black on white! (Remember? We spent _years_ to achieve that.) Dark mode can’t even be _read_ on a laptop outside.

**I might have overlooked something but for life of me can’t find an option to switch everything back to black-on-white.**

Help, please?

### Steps to reproduce (if necessary)
1. Upgrade from 0.13.2 to 0.14.0 
2. Everything becomes dark.

### Expected behavior
Stay as it was. Or have a promonent button somewhere to force "light mode".

### Application configuration
 - **Single mode or Multi-user mode?**  Multi
 - **Database?** [mysql/sqlite] mysql (mariadb)
 - **Open registration?** [yes/no] no
 - **Federation enabled?** [yes/no] yes

**Version or last commit**:
0.14.0

**Comment by thebaer** [comment]
Where did you install from? This should be fixed in the current official build. Or see this comment for a quick fix: https://github.com/writefreely/writefreely/issues/780#issuecomment-1743856347

**Comment by Moonbase59** [comment]
From the releases page here on GitHub, this file: https://github.com/writefreely/writefreely/releases/download/v0.14.0/writefreely_0.14.0_linux_amd64.tar.gz
