### ISSUE TITLE
wrong date on subscribers page

### ISSUE THREAD

**Issue by escuco** [writefreely/writefreely#872]
Hello and many thanks for the last writefreely update v0.15.0 - the upgrade process went smooth.

### Describe the bug
I love the new subscribers pages were I can see, who follows my blog via the fediverse.

Unfortunately the date, since when somebody subscribed, is wrong. Even followers, that subscribed AFTER the update to v0.15.0 have a wrong date "January 1, 0001".

![Screenshot_20240205_143100](https://github.com/writefreely/writefreely/assets/1647405/25fa1940-2322-4e73-b708-3b949ab99744)

### Steps to reproduce (if necessary)
Have a look in your writefreely blog to the subscribers page and click on "followers".

### Expected behavior
The correct subscribe date should be displayed.

### Application configuration
 - **Single mode** 
 - **Database?** [mysql]
 - **Open registration?** [no]
 - **Federation enabled?** [yes]

**Version or last commit**: v0.15.0

**Comment by elkcityhazard** [comment]
I don't actively use writefreely, but what I am seeing is that there is a table called `remoteusers`that is your "followers" but I'm not seeing any timestamp in the database table.

**Comment by elkcityhazard** [comment]
submitted

**Comment by elkcityhazard** [comment]
@thebaer I ended up moving this fix into a new pull request  #883.  Sorry for the extra work.
