### ISSUE TITLE
This page contains the following errors: error on line 1 at column 1: Start tag expected, '<' not found Below is a rendering of the page up to the first error.

### ISSUE THREAD

**Issue by DarkShyMW** [writefreely/writefreely#941]
### Describe the bug
When open /sitemap.xml take error:

This page contains the following errors:
error on line 1 at column 1: Start tag expected, '<' not found
Below is a rendering of the page up to the first error.

### Steps to reproduce (if necessary)
1. Clear install from package
2.  /sitemap.xml
3. ...

### Expected behavior
Should open sitemap

### Application configuration
 - Multi-user mode
 - Mysql
 - Yeap
 - Yeap

v0.15.0

**Comment by thebaer** [comment]
Right now, `sitemap.xml` is only meant to be available on individual blogs -- there isn't an instance-wide sitemap for multi-user instances. So I think the best route for now will be to just return a "not found" page to go along with the `404` status that's already getting returned. I'll submit a fix in a second.
